// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjruogyyicsnptklhgwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcnVvZ3l5aWNzbnB0a2xoZ3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjA4MjksImV4cCI6MjA2MDg5NjgyOX0.K3xzS1I8t4gGwYdEqloicJYrPKHFyY5qBYLVY41usbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);